[package]
name = "rust_ransomware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.4"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
rand = "0.8.5"